import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const support=[["01","BRAND","Build your local education centre with the LCC brand framework."],["02","ACADEMICS","Structured programmes, curriculum and learning resources."],["03","SETUP","Guidance for centre infrastructure, lab and launch."],["04","MARKETING","Resources to support local awareness and admissions."],["05","TECHNOLOGY","Digital systems for examinations, results and certificates."],["06","SUPPORT","Ongoing academic, operational and technical assistance."]];
const modules=["Computer Fundamentals","Operating System","MS Word","MS Excel","PowerPoint","Internet & Email","Database Management","Networking","Programming Fundamentals","Web Design","Cyber Security","Practical Project"];
function App(){const[open,setOpen]=useState(false),[menu,setMenu]=useState(false);const go=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};return <div className="app">
<div className="top"><div className="wrap"><span>LCC EDUCATION & TRAINING CENTRE</span><span>📞 7501669841</span></div></div>
<header><div className="wrap nav"><button className="logo"onClick={()=>go("home")}><span>LCC</span><b>EDUCATION<br/><small>& TRAINING CENTRE</small></b></button><button className="hamb"onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?"open":""}><button onClick={()=>go("home")}>Home</button><button onClick={()=>go("opportunity")}>Opportunity</button><button onClick={()=>go("system")}>The System</button><button onClick={()=>go("courses")}>Courses</button><button onClick={()=>go("contact")}>Contact</button><button className="apply"onClick={()=>setOpen(true)}>Apply Now ↗</button></nav></div></header>

<section className="hero" id="home"><div className="wrap hero-grid"><div className="hero-copy"><div className="eyebrow"><i/> FRANCHISE OPPORTUNITY</div><h1>Your city.<br/><span>Your centre.</span><br/>Your business.</h1><p>Bring practical computer education to your community and build an LCC Education Centre with a structured business and academic framework.</p><div className="actions"><button className="redbtn"onClick={()=>setOpen(true)}>Check Franchise Opportunity ↗</button><button className="textbtn"onClick={()=>go("system")}>See how LCC works ↓</button></div><div className="hero-stats"><div><b>01</b><span>BRAND<br/>FRAMEWORK</span></div><div><b>12</b><span>MONTH<br/>DCA</span></div><div><b>360°</b><span>PARTNER<br/>SUPPORT</span></div></div></div><div className="hero-side"><div className="giant">LCC</div><div className="side-card"><span className="label">THE OPPORTUNITY</span><h3>Build an education business that starts <em>locally.</em></h3><div className="side-row"><span>ACADEMICS</span><b>✓</b></div><div className="side-row"><span>OPERATIONS</span><b>✓</b></div><div className="side-row"><span>MARKETING</span><b>✓</b></div><div className="side-row"><span>TECHNOLOGY</span><b>✓</b></div></div><div className="number">01<span>/04</span></div></div></div></section>

<section className="ticker"><div>EDUCATION BUSINESS</div><b>×</b><div>LOCAL IMPACT</div><b>×</b><div>CAREER SKILLS</div><b>×</b><div>FRANCHISE GROWTH</div><b>×</b><div>EDUCATION BUSINESS</div></section>

<section className="opportunity" id="opportunity"><div className="wrap"><div className="op-head"><div><div className="eyebrow dark"><i/> WHY LCC</div><h2>Don't just start a business.<br/><span>Build an education brand.</span></h2></div><p>LCC gives entrepreneurs a structured platform to launch and operate a computer education centre — so you can focus on your local market, students and growth.</p></div><div className="support-grid">{support.map(([n,t,d])=><article key={n}><div className="n">{n}</div><div className="mini">↗</div><h3>{t}</h3><p>{d}</p><span className="line"/></article>)}</div></div></section>

<section className="system" id="system"><div className="wrap system-grid"><div className="system-copy"><div className="eyebrow"><i/> THE LCC SYSTEM</div><h2>Everything connects<br/>back to <span>your centre.</span></h2><p>A franchise works best when the pieces work together. LCC's proposed ecosystem brings brand, academics, technology, marketing and support around the centre owner.</p><button className="yellowbtn"onClick={()=>setOpen(true)}>Talk to LCC about your location ↗</button></div><div className="system-diagram"><div className="node core">YOUR<br/><strong>CENTRE</strong></div><div className="node n1">BRAND</div><div className="node n2">ACADEMICS</div><div className="node n3">TECH</div><div className="node n4">MARKETING</div><div className="node n5">SUPPORT</div><span className="connection c1"/><span className="connection c2"/><span className="connection c3"/><span className="connection c4"/><span className="connection c5"/></div></div></section>

<section className="numbers"><div className="wrap"><div className="eyebrow dark"><i/> THE MODEL</div><div className="number-grid"><div><b>12</b><span>MONTH FLAGSHIP<br/>DCA PROGRAMME</span></div><div><b>12+</b><span>LEARNING &<br/>PRACTICAL MODULES</span></div><div><b>5</b><span>CORE CENTRE<br/>SUPPORT AREAS</span></div><div><b>01</b><span>LOCAL BUSINESS<br/>OPPORTUNITY</span></div></div></div></section>

<section className="courses" id="courses"><div className="wrap"><div className="course-head"><div><div className="eyebrow dark"><i/> EDUCATION ENGINE</div><h2>Courses that give<br/>your centre <span>something to sell.</span></h2></div><div><p>Lead with practical computer education that can serve students, job seekers and local learners.</p><button className="brochure"onClick={()=>window.open("/assets/lcc-brochure.jpeg","_blank")}>View brochure ↗</button></div></div><div className="dca"><div><span>DCA</span><h3>Diploma in Computer Application</h3><p>12-month structured programme.</p></div><b>12<br/><small>MODULES</small></b></div><div className="course-grid">{modules.map((m,i)=><div key={m}><span>{String(i+1).padStart(2,"0")}</span><strong>{m}</strong><em>↗</em></div>)}</div></div></section>

<section className="journey"><div className="wrap"><div className="eyebrow"><i/> LAUNCH JOURNEY</div><h2>From idea to <span>open doors.</span></h2><div className="steps">{[["01","APPLY","Tell LCC about you and your location."],["02","DISCUSS","Review requirements and opportunity."],["03","BUILD","Prepare the centre with LCC guidance."],["04","LAUNCH","Start admissions and grow locally."]].map(([n,t,d])=><div key={n}><b>{n}</b><div className="step-line"/><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>

<section className="location"><div className="wrap loc-grid"><div><div className="eyebrow dark"><i/> LOCATION FIRST</div><h2>Is your city<br/><span>ready for LCC?</span></h2><p>Tell us where you want to build. We'll discuss the centre requirements and franchise opportunity for your location.</p><div className="loc-form"><input placeholder="Enter city / location"/><button onClick={()=>setOpen(true)}>Check ↗</button></div></div><div className="map"><div className="map-shape"/><span className="pin a">●</span><span className="pin b">●</span><span className="pin c">●</span><span className="pin d">●</span><div className="map-tag">LCC OPPORTUNITY MAP <b>INDIA</b></div></div></div></section>

<section className="cta" id="contact"><div className="wrap"><div className="eyebrow"><i/> MAKE THE MOVE</div><h2>Your city is the<br/><span>next opportunity.</span></h2><p>Start a conversation with LCC about opening an education centre in your location.</p><button className="whitebtn"onClick={()=>setOpen(true)}>Become an LCC Partner ↗</button></div><div className="cta-word">START</div></section>

<footer><div className="wrap foot"><div><div className="flogo"><span>LCC</span><b>LCC EDUCATION<br/><small>& TRAINING CENTRE</small></b></div><p>Learn today. Lead tomorrow.</p></div><div><h4>Explore</h4><button onClick={()=>go("opportunity")}>Why LCC</button><button onClick={()=>go("system")}>The System</button><button onClick={()=>go("courses")}>Courses</button></div><div><h4>Partner</h4><button onClick={()=>setOpen(true)}>Apply Now</button><button onClick={()=>go("opportunity")}>Support</button><button onClick={()=>go("contact")}>Contact</button></div><div><h4>Contact</h4><span>📞 7501669841</span><span>📍 Cooch Behar, 736101</span></div></div><div className="wrap copyright">© 2026 LCC Education & Training Centre</div></footer>

{open&&<div className="modal-bg"onClick={()=>setOpen(false)}><div className="modal"onClick={e=>e.stopPropagation()}><button className="close"onClick={()=>setOpen(false)}>×</button><div className="eyebrow dark"><i/> FRANCHISE APPLICATION</div><h2>Let's build your<br/><span>local opportunity.</span></h2><p>Share your location and we'll start the conversation.</p><form onSubmit={e=>{e.preventDefault();alert("Thank you! Your franchise enquiry has been submitted.");setOpen(false)}}><div><input required placeholder="Full name"/><input required placeholder="Phone number"/></div><input required placeholder="City / Location"/><input placeholder="State"/><select defaultValue=""><option value=""disabled>Do you have a proposed centre space?</option><option>Yes</option><option>No</option><option>Still exploring</option></select><textarea rows="3"placeholder="Tell us about your plan (optional)"/><button className="redbtn full">Submit Application ↗</button></form></div></div>}</div>}
createRoot(document.getElementById("root")).render(<App/>);